RAID = [
   "𝙂𝘼𝙉𝘿 𝙆𝙀 𝘾𝙃𝙃𝙀𝘿 𝙈𝙀 𝙏𝙀𝙍𝙀 𝘼𝙎𝙃𝙒𝘼𝙂𝘼𝙉𝘿𝙃𝘼 𝘿𝘼𝙇𝙆𝙀 𝙋𝙀𝙇𝙐𝙉𝙂𝘼 😂",
   "Sᴀʟᴇ ᴋᴀʜɪɴᴏᴏʀ ʜɪʀᴇ ᴊᴀɪsᴀ ʟᴀᴜɴᴅ ʜᴀɪ ᴍᴇʀᴀ ᴛᴇʀɪ ᴀᴍᴍʏ ᴋᴏ ᴄʜᴀᴛᴀ ᴅᴜɴɢᴀ ɴ ᴍᴀʀ ᴊᴀʏᴇɢɪ😂",
   "ᴠᴀᴄᴄɪɴᴇ ʟᴀɢᴀᴜɴɢᴀ ᴛᴇʀɪ ᴀᴍᴍʏ ᴋᴏ ᴀᴜʀ ᴡᴏ ᴠ ᴄʜᴏᴏᴄʜɪ ᴍᴇ ᴜsᴋᴇ ᴄʜʜᴇᴅ ᴍᴇ 🤣😂",
   "ʝɦǟռȶʊʟʟɛ ֆǟʟɛ ǟɨֆǟ ʍǟʀʊռɢǟ ռ ӄɨ ɦǟɢ ɖɛɢǟ քǟռȶ ӄɛ ɦɨ ʍǟɖǟʀƈɦօɖ 😂",
   "ȶɛʀɨ ǟʍʍʏ ӄɛ ɮɦօӼɖɛ ʍɛ ǟʍƈɦʊʀ ɖǟʟӄɛ ɢɦǟքƈɦǟʊռɢǟᴠᴀᴄᴄɪɴᴇ ʟᴀɢᴀᴜɴɢᴀ ᴛᴇʀɪ ᴀᴍᴍʏ ᴋᴏ ᴀᴜʀ ᴡᴏ ᴠ ᴄʜᴏᴏᴄʜɪ ᴍᴇ ᴜsᴋᴇ ᴄʜʜᴇᴅ ᴍᴇ 🤣😂",
   "𝙑𝙀𝙇𝙑𝙀𝙏 𝙆𝙀 𝙍𝘼𝙅𝘼𝙄 𝙈𝙀 𝘾𝙃𝙊𝘿𝙐𝙉𝙂𝘼 𝙏𝙀𝙍𝙄 𝙈𝘼 𝙆𝙊 𝙎𝘼𝙍𝘼 𝙋𝘼𝙉𝙄 𝙎𝙐𝙆𝙃𝘼 𝘿𝙐𝙉𝙂𝘼 𝘼𝙐𝙍 𝙈𝙐𝙃 𝙈𝙀 𝙐𝙎𝙆𝙀 𝘼𝙋𝙉𝘼 𝙆𝘼𝘾𝙃𝘼 𝘿𝘼𝙇𝘿𝙐𝙉𝙂𝘼 𝙏𝘼𝙆𝙄 𝘾𝙃𝙄𝙇𝙇𝘼𝙔𝙀 𝙉𝙃𝙄 𝙁𝙄𝙍 𝘿𝙃𝙊𝙆𝙀 𝙎𝙀 𝙂𝘼𝙉𝘿 𝙈𝙀 𝙇𝙊𝘿𝘼 𝙅𝙃𝘼𝙏𝙆𝙀 𝙎𝙀 𝘿𝘼𝙇 𝘿𝙐𝙉𝙂𝘼 😂😂",
   "𝙎𝘼𝙉𝙄𝙏𝙄𝙕𝙀𝙍 𝙇𝘼𝙂𝘼 𝙇𝘼𝙂𝘼 𝙆𝙀 𝙋𝙀𝙇𝙐𝙉𝙂𝘼 𝙏𝙀𝙍𝙄 𝙈𝘼 𝙆𝙊 🎉😂",
   "𝐒𝐀𝐋𝐀 𝐆𝐀𝐍𝐃𝐔𝐆𝐈𝐑𝐈 𝐁𝐀𝐍𝐃 𝐊𝐀𝐑 𝐀𝐔𝐑 𝐃𝐀𝐋𝐀 𝐆𝐈𝐑𝐈 𝐒𝐓𝐀𝐑𝐓 𝐊𝐀𝐑𝐃𝐄 𝐊𝐘𝐔𝐊𝐈 𝐓𝐄𝐑𝐄 𝐆𝐇𝐀𝐑 𝐌𝐄 𝐉𝐎 𝐂𝐇𝐎𝐎𝐂𝐇𝐈𝐃𝐇𝐀𝐑𝐈 𝐇𝐀𝐈 𝐍𝐀 𝐌𝐀𝐒𝐓 𝐄𝐀𝐍𝐃𝐈 𝐁𝐀𝐍𝐄𝐆𝐈🔪",
   "𝙎𝙐𝙉𝘼 𝙃𝘼𝙄 𝙏𝙀𝙍𝙀 𝙂𝙃𝘼𝙍 𝙆𝙄 𝘼𝙍𝙏𝙃𝙄𝙆 𝙃𝘼𝙇𝘼𝙆 𝙏𝙃𝙄𝙆 𝙉𝙃𝙄 𝙃𝘼𝙄 ❓𝘼𝙋𝙉𝙄 𝙈𝘼 𝙆𝙊 𝘽𝙃𝙀𝙅 𝙈𝙀𝙍𝙀 𝙋𝘼𝙎𝙎 𝙐𝙎𝙆𝙄 𝘾𝙃𝙐𝙏 𝙆𝙊 𝘼𝘾𝘾𝙃𝘼 𝘽𝙃𝘼𝙑 𝙇𝘼𝙂𝘼𝙐𝙉𝙂𝘼 💯❤️",
   "𝙏𝙀𝙍𝙄 𝘼𝙈𝙈𝙔 𝙏𝙃𝙄𝙆 𝙃𝙊𝙅𝘼𝙔𝙀𝙂𝙄 𝙈𝙐𝙅𝙎𝙀 𝙀𝙆 𝙑𝘼𝘾𝘾𝙄𝙉𝙀 𝙇𝙀𝙅𝘼 9 𝙄𝙉𝘾𝙃 𝙒𝘼𝙇𝘼 𝙇𝙀𝙆𝙀 𝙋𝙀𝙇 𝘿𝙀𝙉𝘼 𝘼𝙋𝙉𝙄 𝙈𝘼 𝙆𝙀 𝙂𝘼𝙉𝘿 𝙈𝘼𝙄 😂👌",
   "𝙇𝙋𝙂 𝙈𝙀𝙄 𝘼𝘼𝙂 𝙇𝘼𝙂𝘼 𝙆𝙀 𝙏𝙀𝙍𝙄 𝙈𝘼 𝙆𝙀 𝘽𝙃𝙊𝙓𝘿𝙀 𝙈𝙀𝙄 𝙁𝙀𝙉𝙆 𝘿𝙐𝙉𝙂𝘼 𝘼𝙔𝙍 𝘽𝙃𝘼𝙂 𝙅𝘼𝙐𝙉𝙂𝘼 𝘼𝙉𝘿𝘼𝙍 𝙅𝘼𝙆𝙀 𝙁𝘼𝙏𝙀𝙂𝘼 𝘼𝙐𝙍 𝙏𝙀𝙍𝙄 𝙈𝘼 𝙆𝙊 𝘽𝙊𝙓𝘿𝘼 𝘾𝙃𝙄𝙏𝙃𝘿𝘼 𝙐𝘿 𝙅𝘼𝙔𝙀𝙂𝘼😂💯",
   "𝙏𝙀𝙍𝙄 𝘽𝙃𝙀𝙉 𝙆𝙊 𝘿𝘼𝙏𝙀 𝙋𝙀 𝙇𝙀𝙅𝘼𝙐𝙉𝙂𝘼 𝘼𝙐𝙍 𝘾𝙊𝙇𝘿 𝘿𝙍𝙄𝙉𝙆 𝙈𝘼𝙄 𝘼𝙋𝙉𝘼 𝙈𝙊𝙊𝙏 𝙈𝙄𝙇𝘼 𝘿𝙐𝙉𝙂𝘼 𝙁𝙄𝙍 𝙋𝙄𝙇𝘼𝙐𝙉𝙂𝘼 𝙐𝙎𝙆𝙊 😂😚",
   "𝙏𝙀𝙍𝙄 𝙈𝘼 𝙆𝙊 𝙎𝘼𝙆𝙊 𝙎𝘼𝙆𝙄 𝙂𝘼𝘼𝙉𝙀 𝙋𝙀 𝙉𝘼𝘾𝙃𝙒𝘼 𝙆𝙀 𝙋3𝙇𝙐𝙉𝙂𝘼 𝙆𝘼𝘾𝙃𝘼 𝙆𝘼𝘾𝙃",
   "𝙏𝙐 𝘽𝙊𝙓𝘿𝙊 𝙆𝙀 𝙂𝙐𝙃 𝙆𝙃𝘼𝙉𝙀 𝘼𝘼𝙇𝘼 𝙄𝙉𝙎𝘼𝙉 𝙃𝘼𝙄 𝙏𝙀𝙍𝙄 𝙈𝘼 𝘽𝙃𝙄 𝘽𝘼𝘿𝙀 𝘾𝙃𝘼𝙒 𝙎𝙀 𝙈𝙀𝙍𝘼 𝙂𝙊𝙊𝙃 𝙆𝙃𝘼𝙏𝙄 𝙃𝘼𝙄🙊😂",
   "𝘼𝘼𝙄𝙎𝘼 𝘾𝙃𝙊𝘿𝙐𝙉𝙂𝘼 𝙉𝘼 𝙅𝙃𝘼𝙉𝙏 𝙆𝙀 𝙅𝙃𝙄𝙉𝙂𝙀 𝘽𝙀𝙏𝙄𝘾𝙃𝙊𝘿 𝙏𝙀𝙍𝙄 𝙉𝘼𝙉𝙊 𝙔𝘼𝘼𝘿 𝘼𝙅𝘼𝙔𝙀𝙉𝙂𝙄 😌😂👍",
   "𝙎𝘼𝙇𝙀 𝙂𝙃𝘼𝘿𝙄 𝙎𝘼𝙍𝙁 𝙆𝙄 𝙊𝙇𝘼𝘿 𝙋𝙀𝙃𝙇𝙀 𝙄𝙎𝙏𝙀𝙈𝘼𝙇 𝙆𝙍𝙊 𝙁𝙄𝙍 𝙑𝙄𝙎𝙒𝘼𝙎 𝙆𝙍𝙊🔪💯😂",
   "𝙏𝙀𝙍𝙀 𝙈𝘼 𝙆𝙄 𝘾𝙃𝙐𝙏 𝙈𝙀𝙄 𝙏𝙍𝘼𝙄𝙉 𝙇𝙀𝙆𝙀 𝙂𝙃𝙐𝙎 𝙅𝘼𝙐𝙉𝙂𝘼 𝙈𝘼𝘿𝘼𝙍𝘾𝙃𝙊𝘿 😂",
   "𝘼𝙋𝙉𝙊 𝘽𝙐𝘼 𝙆𝙊 𝙎𝘼𝙈𝙅𝘼 𝘿𝙀 𝙒𝘼𝙍𝙉𝘼 𝘼𝙄𝙎𝘼 𝙆𝙀𝙀𝙉𝘾𝙃 𝙆𝙀 𝙏𝙃𝘼𝙋𝙋𝘼𝘿 𝙈𝘼𝙍𝙐𝙉𝙂𝘼 𝙈𝘼𝙍 𝙅𝘼𝙔𝙀𝙂𝙄 𝙎𝘼𝙇𝙇𝙄 𝘽𝘼𝙃𝙐𝙍 𝙐𝘾𝙃𝙃𝘼𝙇𝙏𝙄 😂𝙂𝘼𝙉𝘿𝙐 😂 𝙏𝙀𝙍𝙀 😍 𝙈𝘼 𝙆𝙀  𝘾𝙃𝙐𝙏 ❤️ 𝙈𝙀𝙄 𝙂𝙃𝙐𝙎 𝙆𝙀 𝘿𝙄𝙋𝘼𝙒𝘼𝙇𝙄 𝙈𝘼𝙉𝘼𝙐𝙉𝙂𝘼 😂🔱",
   "𝘿𝙄𝙒𝘼𝙇𝙄 𝙆𝙀 𝘿𝙄𝙉 𝙅𝙄𝙎 𝘾𝙃𝙐𝙉𝙉𝙀 𝙎𝙀 𝙂𝙃𝘼𝙍 𝙋𝙀𝙉𝙏 𝙆𝙍𝙏𝙀 𝙃𝘼𝙄 𝙐𝙎𝙄 𝙎𝙀 𝙏𝙀𝙍𝙀 𝙈𝘼 𝙆𝙄 𝙂𝘼𝙉𝘿 𝙇𝘼𝙇 𝙆𝘼𝘿𝙆𝙀 𝙋𝙀𝙇𝙐𝙉𝙂𝘼",
   "𝙏𝙀𝙍𝙀 𝘽𝙐𝘼 𝙆𝙀 𝘽𝙃𝙊𝙓𝘿𝙀 𝙈𝙀𝙄 𝙇𝙐𝙓 𝙎𝘼𝘽𝙊𝙊𝙉 𝘿𝘼𝙇 𝙆𝙀 𝘾𝙃𝙊𝘿𝙐𝙉𝙂𝘼 𝙍𝘼𝙉𝘿𝙄 𝙆𝙀 𝙊𝙇𝘼𝘿 !!",
   "𝙂𝘼𝙇𝘼𝙏 𝙋𝘼𝙉𝙂𝘼 𝙇𝙀 𝙇𝙄𝙔𝙀 𝘽𝙀𝙏𝘼 👹𝙏𝙐 𝘼𝘽 𝘽𝙃𝙐𝙂𝘼𝙏 𝘽𝙊𝙎𝘿𝘼𝙄 𝙆𝙀 😂",
   "𝙏𝙀𝙍𝙄 𝙈𝘼 𝙆𝙄 𝘾𝙃𝙐𝙏 𝙈𝙀𝙄 𝘼𝙆47 𝙎𝙀 𝙂𝙊𝙇𝙄 𝙈𝘼𝙍𝙐𝙉𝙂𝘼 𝘿𝙃𝘼𝙆 𝘿𝙃𝘼𝙆 𝘿𝙃𝘼𝙆 𝘿𝙃𝘼𝙆 😂😚
   "𝙏𝙀𝙍𝙄 𝙈𝘼 𝙆𝙀 𝙃𝘼𝙏𝙃 𝙆𝙊 𝙋𝙀𝙀𝘾𝙃𝙀 𝙆𝙄 𝙏𝘼𝙍𝘼𝙁 𝙈𝙐𝘿𝘼 𝙆𝙀 𝙐𝙎𝙆𝙀 𝙂𝘼𝙉𝘿 𝙈𝙀𝙄 𝘼𝙋𝙉𝘼 𝙇𝙊𝘿𝘼 𝘿𝘼𝙇 𝘿𝙐𝙉𝙂𝘼 𝘼𝙐𝙍 𝙒𝙊 𝘼𝙇𝘼𝙇𝘼 𝙆𝙀 𝙈𝘼𝙍𝙅𝘼𝙔𝙀𝙄 💯💋😂🙈",
   "𝘽𝘼𝘼𝙋 𝘽𝙊𝙇 𝙈𝘼𝘿𝘼𝙍𝘾𝙃𝙊𝘿 𝙂𝘼𝙉𝘿 𝙆𝙄 𝙋𝘼𝙄𝘿𝘼𝙄𝙎 😂",
   "𝙅𝙃𝘼𝙏𝙐 𝙎𝘼𝙇𝙀 𝙏𝙀𝙍𝙄 𝘽𝙃𝙀𝙉 𝙆𝙄 𝘾𝙃𝙐𝙏 𝙋𝙀 𝘾𝘼𝙆𝙀 𝙇𝘼𝙂𝘼 𝙆𝙀 𝘾𝙃𝘼𝙏 𝙅𝘼𝙐𝙉𝙂𝘼 👾👹",
   "Teri ammy ka life insurance krwa ke usko aisa ch0dunga ki wo marjayegi 🤣",
   "𝙅𝙃𝘼𝘿𝙐 𝙐𝙏𝙃𝘼 𝙆𝙀 𝙏𝙀𝙍𝙀 𝙂𝘼𝙉𝘿 𝙈𝙀𝙄 𝘿𝘼𝙇 𝙆𝙀 𝙏𝙐𝙅𝙃𝙀 𝙈𝙊𝙍𝙀 𝘽𝘼𝙉𝘼 𝘿𝙐𝙉𝙂𝘼 𝘽𝙊𝙎𝘼𝘿𝙄 𝙆𝙀 😂👍",
   "𝙇𝙖̃𝙉𝙙 𝘾𝙃𝙐𝙎𝙀𝙂𝘼 𝙈𝙀𝙍𝘼 𝙈𝘼𝘿𝘼𝙍𝘾𝙃𝙤̀𝘿 𝘽𝙃𝙀𝙉 𝙆𝙀 𝙇𝙊𝘿𝙀𝙀𝙀𝙀😆💯",
   "𝙏𝙀𝙍𝙄 𝙈𝘼 𝙆𝙊 𝙅𝙃𝙐𝙇𝘼 𝙅𝙃𝙐𝙇𝘼 𝙆𝙀 𝙆𝘼𝘾𝙃 𝙆𝘼𝘾𝙃 𝙋3𝙇𝙐𝙉𝙂𝘼 👐👐👃",
   "𝘽𝙃𝙀𝙉 𝙆𝙊 𝙏𝙀𝙍𝙄 𝘾𝙃𝙊𝘾𝙊𝙇𝘼𝙏𝙀 𝙆𝙃𝘼𝙍𝙄𝘿 𝙆𝙀 𝙐𝙎𝙆𝙀 𝘾𝙃𝙐𝙏 𝙈𝙀𝙄 𝘿𝘼𝙇 𝘿𝙐𝙉𝙂𝘼 👻",
   "teri behn ko jhule pe baitha ke uski ch00t pe apna garam l0da touch karaunga🤣⚔️",
   "Teri behn ko uske college ke library me hi ch0d ke pregnant krdunga l0du😈",
   "Teri behn ke muh me l0da dal ke usse papa bulwaunga khud ko☠️",
   "Bhains jaisi ammy ke aulaad sale l0du jaise shakal ke 😈",
   "tere baap ko bich sadak pe gira gira ke m@runga aur last me uske muh pe m00t kr jaunga 😈",
   "Teri ammy ko Ghar me ghuma ke impress krke fir usi thar ke bonat pe leta ke uski gulabi ch00t lunga🚬",
   "Jh@nt ke pissu sale l0du kahi ke r@nd ki olad🔏😈⚠️",
   "Teri ammy ke bhxde ko jalte huye koyle pe shek ke pelunga⚠️😈",
   "Teri behn ko sardi ki thandi me chhat pe nanga krke ch0dunga m@charch0d🔥😈",
   "Teri ammy ka blowj faad ke uske ch00chi pe apna l0da marunga aur kacha kach pelunga😂⚠️",
   "𝙅𝘽 𝙈𝘼𝙄 𝙏𝙀𝙍𝙄 𝙈𝘼 𝙆𝙀 𝙂𝘼𝙉𝘿 𝙈𝙀𝙄 𝙇𝘼𝙉𝘿 𝘿𝘼𝙇𝙉𝙀 𝙂𝘼𝙔𝘼 𝙏𝙊𝙃 𝙈𝙀𝙍𝘼 𝙇𝘼𝙉𝘿 𝙃𝙄 𝙈𝙐𝘿 𝙂𝙔𝘼😂",
   "𝘾𝙃𝘼𝙇𝙏𝙄 𝙎𝘼𝘿𝘼𝙆 𝙋𝙀 𝙏𝙀𝙍𝙄 𝙈𝘼 𝙆𝙀 𝙈𝙐𝙃 𝙈𝙀𝙄 𝘿𝙀 𝘿𝙀𝙏𝘼 𝙃𝙐𝙉 𝙈𝘼𝙄 😂😂😂😂😂😂😂",
   "4,4 𝘾𝙊𝙉𝘿𝙊𝙈 𝙐𝙎𝙀 𝙆𝙄𝙔𝙀 𝙀𝙆 𝘿𝙄𝙉 𝙈𝙀𝙄 𝙏𝙀𝙍𝙄 𝘾𝙃𝙊𝙏𝙄 𝘽𝙃𝙀𝙉 𝙋𝙀👹",
   "𝘽𝙐𝙆𝙃𝘼𝙍 𝙃𝙊𝙏𝙀 𝙃𝙐𝙔𝙀 𝙋𝙀𝙇𝘼 𝙏𝙀𝙍𝙄 𝘽𝙃𝙀𝙉 𝙆𝙊",
   "𝙏𝙀𝙍𝙄 𝙈𝘼 𝘽𝘼𝙃𝙐𝙍 𝙅𝘼𝘼𝙉𝘿𝘼𝘼𝙍 𝙃𝘼𝙄 𝙎𝘼𝙇𝙄 𝘾𝙃𝙄𝙇𝙇𝘼𝙄 𝙏𝘼𝙆 𝙉𝙃𝙄 𝙅𝘼𝘽 𝙈𝘼𝙄𝙉𝙀 𝙐𝙎𝙆𝙀 𝙎𝘼𝙏𝙃 𝘼𝙉𝘼𝙇 𝙆𝙄𝙔𝘼 😂😘",
   "𝙏𝙀𝙍𝙄 𝘽𝙃𝙀𝙉 𝙅𝙄𝙎𝙎 𝙃𝙊𝙎𝙏𝙇𝙀 𝙈𝙀𝙄 𝙍𝙀𝙃𝙏𝙄 𝙉 𝙐𝙎𝙆𝙊 𝙍𝙊𝙅 𝘿𝙀𝙀𝙒𝘼𝙇 𝙆𝙐𝘿𝘼𝙏𝙏𝘼 𝙃𝙐𝙉 𝙈𝘼𝙄 😶😶",
   "𝙏𝙀𝙍𝙄 𝘽𝙃𝙀𝙉 𝙈𝙀𝙍𝙀 𝙆𝘼𝘾𝘾𝙃𝙀 𝙆𝙊 𝘼𝙋𝙉𝘼 𝙈𝘼𝙎𝙆 𝙎𝘼𝙈𝘼𝙅𝙃 𝙆𝙀 𝙋𝙀𝙃𝙉𝙏𝙄 𝙃𝘼𝙄 😂",
   "𝘼𝙋𝙉𝙊 𝘽𝙐𝘼 𝙆𝙊 𝙎𝘼𝙈𝙅𝘼 𝘿𝙀 𝙒𝘼𝙍𝙉𝘼 𝘼𝙄𝙎𝘼 𝙆𝙀𝙀𝙉𝘾𝙃 𝙆𝙀 𝙏𝙃𝘼𝙋𝙋𝘼𝘿 𝙈𝘼𝙍𝙐𝙉𝙂𝘼 𝙈𝘼𝙍 𝙅𝘼𝙔𝙀𝙂𝙄 𝙎𝘼𝙇𝙇𝙄 𝘽𝘼𝙃𝙐𝙍 𝙐𝘾𝙃𝙃𝘼𝙇𝙏𝙄 😂",
   "𝘽𝙄𝙇𝙇𝙄𝘾𝙃𝙊𝘿𝙀 𝙎𝘼𝙇𝙀 𝘽𝘼𝘼𝙋 𝙎𝙀 𝙂𝘼𝙉𝘿𝙈𝘼𝙎𝙏𝙄 𝙆𝘼𝙍𝙀𝙂𝘼 𝙏𝙐 😂",
   "𝙏𝙀𝙍𝙄 𝙈𝘼 𝙆𝙄 𝘾𝙃𝙐𝙏 𝙆𝙄𝙏𝙉𝘼 𝘾𝙃𝙊𝙏𝘼 𝙃𝘼𝙄 𝙍𝙀 𝙆𝘼𝙄𝙎𝙀 𝘽𝘼𝙃𝘼𝙍 𝘼𝙔𝘼 𝙏𝙐😂😂",
   "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗣𝗥𝗜𝗩𝗔𝗧𝗘 𝗩𝗜𝗟𝗟𝗔 𝗟𝗘 𝗝𝗔𝗔𝗞𝗥 𝗣𝗘𝗟𝗨𝗡𝗚𝗔 😂🍆💋🍑",
    "𝗜 𝗙𝗨𝗖𝗞𝗘𝗗 𝗨𝗥 𝗠𝗢𝗠 😂🍆",
    "𝗬𝗢𝗨𝗥 𝗠𝗢𝗧𝗛𝗘𝗥 𝗪𝗜𝗟𝗟 𝗦𝗨𝗖𝗞 𝗠𝗬 𝗗𝗜𝗖𝗞😂🍆🍑",
    "𝗬𝗢𝗨𝗥 𝗠𝗢𝗧𝗛𝗘𝗥 𝗔𝗡𝗗 𝗦𝗜𝗦𝗧𝗘𝗥 𝗜𝗦 𝗩𝗘𝗥𝗬 𝗛𝗢𝗧𝗧 𝗠𝗔𝗡 𝗦𝗛𝗘 𝗦𝗨𝗖𝗞'𝗦 𝗠𝗬 𝗗𝗜𝗖𝗞 𝗘𝗩𝗘𝗥𝗬𝗗𝗔𝗬🙈🍆💦",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔𝗔 𝗫𝗫𝗫 𝗩𝗜𝗥𝗔𝗟 𝗞𝗥 𝗗𝗨𝗡𝗚𝗔 𝗕𝗔𝗫𝗖𝗛𝗘 🥵💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗜𝗬𝗔 𝗖𝗛𝗨𝗗𝗞𝗘 𝗗𝗔𝗥 𝗚𝗔𝗬𝗜 𝗬𝗔𝗔𝗥💦👻🙈",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗔𝗕 𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗞𝗔 𝗠𝗜𝗗𝗗𝗟𝗘 𝗙𝗜𝗡𝗚𝗘𝗥 𝗡𝗔𝗜𝗟 𝗡𝗔𝗛𝗜 𝗛𝗔𝗜😂👻🍑🍆💦",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔 𝗫𝗛𝗨𝗗𝗔𝗜 𝗔𝗟𝗜𝗩𝗘 𝗣𝗜𝗖 𝗗𝗔𝗔𝗟 𝗗𝗨𝗡𝗚𝗔 🤤😂",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗖𝗛𝗢𝗗𝗧𝗘 𝗪𝗔𝗞𝗧 𝗬𝗢𝗨𝗧𝗨𝗕𝗘 𝗣𝗘 𝗟𝗜𝗩𝗘 𝗞𝗔𝗥𝗨𝗡𝗚𝗔😂🍆🍑💦",
    "𝗔𝗕𝗜 𝗩 𝗧𝗜𝗠𝗘 𝗛 𝗠𝗔𝗗𝗔𝗥𝗫𝗛𝗢𝗗 𝗣𝗔𝗣𝗔 𝗕𝗢𝗟 𝗔𝗨𝗥 𝗟𝗨𝗡𝗗 𝗣𝗞𝗔𝗗 🤣🥵💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘𝗘 𝗫𝗛𝗨𝗧  𝗠𝗔𝗜 𝗥𝗢𝗖𝗞𝗘𝗧 𝗟𝗔𝗨𝗡𝗖𝗛 𝗞𝗥 𝗗𝗨𝗡𝗚𝗔 𝗡𝗔𝗦𝗔 𝗪𝗔𝗟𝗔 🤤💋😱",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗚𝗔𝗥𝗔𝗠 𝗚𝗔𝗥𝗔𝗠 𝗧𝗘𝗟 🥺🤣💋",
    "𝗧𝗘𝗥𝗘 𝗕𝗔𝗔𝗣 𝗔𝗔𝗚𝗬𝗘 𝗠𝗔𝗗𝗔𝗥𝗫𝗛𝗢𝗗 𝗞𝗔𝗟𝗔𝗣 𝗠𝗧 𝗔𝗕 🤣🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗔𝗔𝗔 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗘𝗞 𝗔𝗨𝗥 𝗫𝗛𝗨𝗧 𝗗𝗔𝗟𝗪𝗔 𝗗𝗨𝗡𝗚𝗔 𝗥𝗡𝗗𝗜 🤤💋🔥",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗘𝗘 𝗫𝗛𝗨𝗧 𝗣𝗘 𝗖𝗥𝗜𝗖𝗞𝗘𝗧 𝗞𝗛𝗘𝗟𝗡𝗚𝗘 🤣😱",
    "𝗨𝗙𝗙 𝗖𝗛𝗨𝗗 𝗚𝗔𝗬𝗔 𝗕𝗘𝗧𝗔 𝗔𝗕 𝗕𝗛𝗢𝗞 𝗖𝗛𝗨𝗧𝗜𝗬𝗔 𝗕𝗔𝗔𝗣 𝗦𝗘 𝗟𝗔𝗗𝗡𝗘 𝗔𝗔𝗬𝗔 𝗧𝗛𝗔 𝗡𝗔😂🍆🍑👻",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗞𝗜 𝗣𝗨𝗦𝗦𝗬 𝗖𝗛𝗔𝗧𝗨𝗡𝗚𝗔 𝗕𝗘𝗧𝗘😂🍑🍆🤤",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔 𝗥𝗔𝗡𝗗𝗜 𝗞𝗛𝗔𝗡𝗘 𝗞𝗜 𝗠𝗔𝗡𝗔𝗚𝗘𝗥 🤤💋",
    "𝗞𝗬𝗔 𝗠𝗧𝗟𝗕 𝗞𝗜 𝗠𝗔𝗔 𝗞𝗢 𝗫𝗛𝗢𝗗 𝗟𝗢 𝗣𝗔𝗥 𝗣𝗔𝗜𝗦𝗘 𝗗𝗘𝗧𝗘 𝗝𝗔𝗔𝗡𝗔 🤣🔥🤤💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗨𝗠𝗠𝗬 𝗠𝗘𝗥𝗘 𝗟𝗢𝗗𝗘 𝗞𝗜 𝗙𝗔𝗡 𝗛𝗔𝗜😍👻💋🍆",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗢 𝗫𝗛𝗢𝗗 𝗞𝗘 𝗧𝗘𝗥𝗘 𝗕𝗔𝗔𝗣 𝗞𝗔𝗔𝗔 𝗟𝗨𝗡𝗗 𝗞𝗔𝗔𝗧 𝗗𝗨𝗡𝗚𝗔 🤣🔥",
    "𝗞𝗬𝗔 𝗠𝗔𝗧𝗟𝗕 𝗣𝗔𝗣𝗔 𝗚𝗔𝗟𝗧𝗜 𝗛𝗢 𝗚𝗔𝗬𝗜 𝗠𝗔𝗔𝗙 𝗞𝗔𝗥𝗗𝗢😁🍑🍆👻",
    "𝗔𝗣𝗡𝗜 𝗠𝗔𝗔 𝗞𝗔𝗔𝗔 𝗚𝗔𝗔𝗔𝗡𝗗 𝗗𝗘𝗗𝗢 🥺 𝗧𝗛𝗢𝗗𝗜 𝗗𝗘𝗥 𝗣𝗘𝗟 𝗞𝗘 𝗗𝗘𝗧𝗔 𝗛𝗨 🤤💋",
    "𝗧𝗘𝗥𝗜 𝗠𝗔𝗔𝗔 𝗞𝗘𝗘 𝗫𝗛𝗨𝗧 𝗠𝗔𝗜 𝗚𝗛𝗔𝗥 𝗕𝗡𝗔 𝗗𝗨𝗡𝗚𝗔 𝗟𝗢𝗗𝗘 🤤💋",
]


RRAID = [
    "MADARCHOD",
    "BHOSDIKE",
    "LAAAWEEE KE BAAAAAL",
    "MAAAAR KI JHAAAAT KE BBBBBAAAAALLLLL",
    "MADRCHOD..",
    "TERI MA KI CHUT..",
    "LWDE KE BAAALLL.",
    "MACHAR KI JHAAT KE BAAALLLL",
    "TERI MA KI CHUT M DU TAPA TAP?",
    "TERI MA KA BHOSDAA",
    "TERI BHN SBSBE BDI RANDI.",
    "TERI MA OSSE BADI RANDDDDD",
    "TERA BAAP CHKAAAA",
    "KITNI CHODU TERI MA AB OR..",
    "TERI MA CHOD DI HM NE",
    "TERI MA KE STH REELS BNEGA ROAD PEE",
    "TERI MA KI CHUT EK DAM TOP SEXY",
    "MALUM NA PHR KESE LETA HU M TERI MA KI CHUT TAPA TAPPPPP",
    "LUND KE CHODE TU KEREGA TYPIN",
    "SPEED PKD LWDEEEE",
    "BAAP KI SPEED MTCH KRRR",
    "LWDEEE",
    "PAPA KI SPEED MTCH NHI HO RHI KYA",
    "ALE ALE MELA BCHAAAA",
    "CHUD GYA PAPA SEEE",
    "KISAN KO KHODNA OR",
    "SALE RAPEKL KRDKA TERA",
    "HAHAHAAAAA",
    "KIDSSSS",
    "TERI MA CHUD GYI AB FRAR MT HONA",
    "YE LDNGE BAPP SE",
    "KIDSSS FRAR HAHAHH",
    "BHEN KE LWDE SHRM KR",
    "KITNI GLIYA PDWEGA APNI MA KO",
    "NALLEE",
    "SUAR KE PILLE TERI MAAKO SADAK PR LITAKE CHOD DUNGA 😂😆🤤",
    "ABE TERI MAAKA BHOSDA MADERCHOOD KR PILLE PAPA SE LADEGA TU 😼😂🤤",
    "GALI GALI NE SHOR HE TERI MAA RANDI CHOR HE 💋💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE PILLE KUTTE KE CHODE 😂👻🔥",
    "TERI MAAKO AISE CHODA AISE CHODA TERI MAAA BED PEHI MUTH DIA 💦💦💦💦",
    "TERI BEHEN KE BHOSDE ME AAAG LAGADIA MERA MOTA LUND DALKE 🔥🔥💦😆😆",
    "RANDIKE BACHHE TERI MAAKO CHODU CHAL NIKAL",
    "KITNA CHODU TERI RANDI MAAKI CHUTH ABB APNI BEHEN KO BHEJ 😆👻🤤",
    "TERI BEHEN KOTO CHOD CHODKE PURA FAAD DIA CHUTH ABB TERI GF KO BHEJ 😆💦🤤",
    "TERI GF KO ETNA CHODA BEHEN KE LODE TERI GF TO MERI RANDI BANGAYI ABB CHAL TERI MAAKO CHODTA FIRSE ♥️💦😆😆😆😆",
    "HARI HARI GHAAS ME JHOPDA TERI MAAKA BHOSDA 🤣🤣💋💦",
    "CHAL TERE BAAP KO BHEJ TERA BASKA NHI HE PAPA SE LADEGA TU",
    "TERI BEHEN KI CHUTH ME BOMB DALKE UDA DUNGA MAAKE LAWDE",
    "TERI MAAKO TRAIN ME LEJAKE TOP BED PE LITAKE CHOD DUNGA SUAR KE PILLE 🤣🤣💋💋",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI MAAAKE NUDES GOOGLE PE UPLOAD KARDUNGA BEHEN KE LAEWDE 👻🔥",
    "TERI BEHEN KO CHOD CHODKE VIDEO BANAKE XNXX.COM PE NEELAM KARDUNGA KUTTE KE PILLE 💦💋",
    "TERI MAAAKI CHUDAI KO PORNHUB.COM PE UPLOAD KARDUNGA SUAR KE CHODE 🤣💋💦",
    "ABE TERI BEHEN KO CHODU RANDIKE BACHHE TEREKO CHAKKO SE PILWAVUNGA RANDIKE BACHHE 🤣🤣",
    "TERI MAAKI CHUTH FAADKE RAKDIA MAAKE LODE JAA ABB SILWALE 👄👄",
    "TERI BEHEN KI CHUTH ME MERA LUND KAALA",
    "TERI BEHEN LETI MERI LUND BADE MASTI SE TERI BEHEN KO MENE CHOD DALA BOHOT SASTE SE",
    "BETE TU BAAP SE LEGA PANGA TERI MAAA KO CHOD DUNGA KARKE NANGA 💦💋",
    "HAHAHAH MERE BETE AGLI BAAR APNI MAAKO LEKE AAYA MATH KAT OR MERE MOTE LUND SE CHUDWAYA MATH KAR",
    "CHAL BETA TUJHE MAAF KIA 🤣 ABB APNI GF KO BHEJ",
    "SHARAM KAR TERI BEHEN KA BHOSDA KITNA GAALIA SUNWAYEGA APNI MAAA BEHEN KE UPER",
    "ABE RANDIKE BACHHE AUKAT NHI HETO APNI RANDI MAAKO LEKE AAYA MATH KAR HAHAHAHA",
    "KIDZ MADARCHOD TERI MAAKO CHOD CHODKE TERR LIYE BHAI DEDIYA",
    "JUNGLE ME NACHTA HE MORE TERI MAAKI CHUDAI DEKKE SAB BOLTE ONCE MORE ONCE MORE 🤣🤣💦💋",
    "GALI GALI ME REHTA HE SAND TERI MAAKO CHOD DALA OR BANA DIA RAND 🤤🤣",
    "SAB BOLTE MUJHKO PAPA KYOUNKI MENE BANADIA TERI MAAKO PREGNENT 🤣🤣",
    "SUAR KE PILLE TERI MAAKI CHUTH ME SUAR KA LOUDA OR TERI BEHEN KI CHUTH ME MERA LODA",
    "CHAL CHAL APNI MAAKI CHUCHIYA DIKA",
    "HAHAHAHA BACHHE TERI MAAAKO CHOD DIA NANGA KARKE",
    "TERI GF HE BADI SEXY USKO PILAKE CHOODENGE PEPSI",
    "2 RUPAY KI PEPSI TERI MUMMY SABSE SEXY 💋💦",
    "TERI MAAKO CHEEMS SE CHUDWAVUNGA MADERCHOOD KE PILLE 💦🤣",
    "TERI BEHEN KI CHUTH ME MUTHKE FARAR HOJAVUNGA HUI HUI HUI",
    "SPEED LAAA TERI BEHEN CHODU RANDIKE PILLE 💋💦🤣",
    "ARE RE MERE BETE KYOUN SPEED PAKAD NA PAAA RAHA APNE BAAP KA HAHAH🤣🤣",
    "SUN SUN SUAR KE PILLE JHANTO KE SOUDAGAR APNI MUMMY KI NUDES BHEJ",
    "ABE SUN LODE TERI BEHEN KA BHOSDA FAAD DUNGA",
    "TERI MAAKO KHULE BAJAR ME CHOD DALA 🤣🤣💋",
    "SHRM KR",
    "MERE LUND KE BAAAAALLLLL",
    "KITNI GLIYA PDWYGA APNI MA BHEN KO",
    "RNDI KE LDKEEEEEEEEE",
    "KIDSSSSSSSSSSSS",
    "Apni gaand mein muthi daal",
    "Apni lund choos",
    "Apni ma ko ja choos",
    "Bhen ke laude",
    "Bhen ke takke",
    "Abla TERA KHAN DAN CHODNE KI BARIII",
    "BETE TERI MA SBSE BDI RAND",
    "LUND KE BAAAL JHAT KE PISSSUUUUUUU",
    "LUND PE LTKIT MAAALLLL KI BOND H TUUU",
    "KASH OS DIN MUTH MRKE SOJTA M TUN PAIDA NA HOTAA",
    "GLTI KRDI TUJW PAIDA KRKE",
    "SPEED PKDDD",
    "Gaand main LWDA DAL LE APNI MERAAA",
    "Gaand mein bambu DEDUNGAAAAAA",
    "GAND FTI KE BALKKK",
    "Gote kitne bhi bade ho, lund ke niche hi rehte hai",
    "Hazaar lund teri gaand main",
    "Jhaant ke pissu-",
    "TERI MA KI KALI CHUT",
    "Khotey ki aulda",
    "Kutte ka awlat",
    "Kutte ki jat",
    "Kutte ke tatte",
    "TETI MA KI.CHUT , tERI MA RNDIIIIIIIIIIIIIIIIIIII",
    "Lavde ke bal",
    "muh mei lele",
    "Lund Ke Pasine",
    "MERE LWDE KE BAAAAALLL",
    "HAHAHAAAAAA",
    "CHUD GYAAAAA",
    "Randi khanE KI ULADDD",
    "Sadi hui gaand",
    "Teri gaand main kute ka lund",
    "Teri maa ka bhosda",
    "Teri maa ki chut",
    "Tere gaand mein keede paday",
    "Ullu ke pathe",
    "SUNN MADERCHOD",
    "TERI MAA KA BHOSDA",
    "BEHEN K LUND",
    "TERI MAA KA CHUT KI CHTNIIII",
    "MERA LAWDA LELE TU AGAR CHAIYE TOH",
    "GAANDU",
    "CHUTIYA",
    "TERI MAA KI CHUT PE JCB CHADHAA DUNGA",
    "SAMJHAA LAWDE",
    "YA DU TERE GAAND ME TAPAA TAP��",
    "TERI BEHEN MERA ROZ LETI HAI",
    "TERI GF K SAATH MMS BANAA CHUKA HU���不�不",
    "TU CHUTIYA TERA KHANDAAN CHUTIYA",
    "AUR KITNA BOLU BEY MANN BHAR GAYA MERA�不",
    "TERIIIIII MAAAA KI CHUTTT ME ABCD LIKH DUNGA MAA KE LODE",
    "TERI MAA KO LEKAR MAI FARAR",
    "RANIDIII",
    "BACHEE",
    "CHODU",
    "RANDI",
    "RANDI KE PILLE",
    "TERIIIII MAAA KO BHEJJJ",
    "TERAA BAAAAP HU",
    "teri MAA KI CHUT ME HAAT DAALLKE BHAAG JAANUGA",
    "Teri maa KO SARAK PE LETAA DUNGA",
    "TERI MAA KO GB ROAD PE LEJAKE BECH DUNGA",
    "Teri maa KI CHUT MÉ KAALI MITCH",
    "TERI MAA SASTI RANDI HAI",
    "TERI MAA KI CHUT ME KABUTAR DAAL KE SOUP BANAUNGA MADARCHOD",
    "TERI MAAA RANDI HAI",
    "TERI MAAA KI CHUT ME DETOL DAAL DUNGA MADARCHOD",
    "TERI MAA KAAA BHOSDAA",
    "TERI MAA KI CHUT ME LAPTOP",
    "Teri maa RANDI HAI",
    "TERI MAA KO BISTAR PE LETAAKE CHODUNGA",
    "TERI MAA KO AMERICA GHUMAAUNGA MADARCHOD",
    "TERI MAA KI CHUT ME NAARIYAL PHOR DUNGA",
    "TERI MAA KE GAND ME DETOL DAAL DUNGA",
    "TERI MAAA KO HORLICKS PILAUNGA MADARCHOD",
    "TERI MAA KO SARAK PE LETAAA DUNGAAA",
    "TERI MAA KAA BHOSDA",
    "MERAAA LUND PAKAD LE MADARCHOD",
    "CHUP TERI MAA AKAA BHOSDAA",
    "TERIII MAA CHUF GEYII KYAAA LAWDEEE",
    "TERIII MAA KAA BJSODAAA",
    "MADARXHODDD",
    "TERIUUI MAAA KAA BHSODAAA",
    "TERIIIIII BEHENNNN KO CHODDDUUUU MADARXHODDDD",
    "NIKAL MADARCHOD",
    "RANDI KE BACHE",
    "TERA MAA MERI FAN",
    "TERI SEXY BAHEN KI CHUT OP",
]
